  trigger:

  - master
  
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
      checkLatest: true
  
  - task: CmdLine@2
    displayName: 'Build'
    inputs:
      script: |
        npm install -g @angular/cli
        npm install
        ng build --prod

  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'pet-book'
      command: 'build'
      Dockerfile: '**/Dockerfile'
  
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'pet-book'
      command: 'push'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'dist'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true