version: 2

jobs:
  build:
    working_directory: ~/pet-book
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run: 
          name: Install local dependencies
          command: npm ci
      - run:
          name: Install libXext.i686
          command: sudo apt-get install libXext.x86_64 -y
      - run:
          name: Install libXext.i686
          command: sudo apt-get install libXrender.x86_64 -y
      - run:
          name: Install libXext.i686
          command: sudo apt-get install libXtst.x86_64 -y
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      - run: 
          name: unit-test
          command: npm run test-ci-2