job_defaults: &job_defaults
  docker:
  - image: circleci/node:latest-browsers
    environment:
      CHROME_BIN: /usr/bin/google-chrome
  working_directory: ~/pet-book

jobs:
  static-code-scan:
    <<: *job_defaults
    steps:
      - checkout
      - sonarcloud/scan
  
  test:
    <<: *job_defaults
    steps:
      - checkout
      - run: 
          name: Install local dependencies
          command: npm install
      - run:
          name: test application
          command: npm run test-ci
  
  build:
    <<: *job_defaults
    steps:
      - checkout
      - run: 
          name: Install local dependencies
          command: npm install
      - run:
          name: build
          command: npm run build --prod

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
  aws-s3: circleci/aws-s3@2.0.0

version: 2.1
workflows:
  main:
    jobs:
      - build
      - test
      - static-code-scan:
        context: sonarCloud