jobs:
  build:
    working_directory: ~/pet-book
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: install node
          command: sudo apt-get install -y nodejs
      - checkout
      - sonarcloud/scan
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-i
      - run: 
          name: Install local dependencies
          command: npm ci
      - run:
          name: install angular/cli
          command: npm install @angular/cli
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud