version: 2

jobs:
  build:
    working_directory: ~/pet-book
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: install node
          command: sudo apt-get install -y nodejs
      - run:
          name: install angular/cli
          command: npm install @angular/cli
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-i
      - run: 
          name: Install local dependencies
          command: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      - run: 
          name: unit-test
          command: npm run test-ci-2